version: 2

updates:
    - package-ecosystem: npm
      directory: "/React.js - Part I/phone-directory-app/"
      schedule:
          interval: daily
      open-pull-requests-limit: 10
      labels:
          - dependencies
      versioning-strategy: increase
